language: node_js
node_js: stable

cache:
    directories:
        - node_modules

before_install:
    - git clone https://github.com/zpike/hexo-theme-apollo.git themes/apollo

# S: Build Lifecycle
install:
  - npm install

script:
  - hexo generate

after_success:
  - hexo deploy

branches:
  only:
    - blog-source
