language: node_js
node_js: stable

before_install:
    - git clone https://github.com/zpike/hexo-theme-apollo.git themes/apollo

# S: Build Lifecycle
install:
  - npm install

#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_success:
  - hexo d 

branches:
  only:
    - blog-source
