language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "zpike"
  - git config user.email "conan401@126.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog-source
env:
 global:
   - GH_REF: https://github.com/zpike/zpike.github.io.git